version: 2.0
jobs:
  deploy-prd:
    machine:
      node:
        version: 12
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm install eslint
      - run:
          name: Install ReviewDog
          command: curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b ./bin
      - run:
          name: Run ReviewDog
          shell: /bin/sh
          command: docker-compose run test npm lint | ./bin/reviewdog -reporter=github-pr-review -f=eslint

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-prd: {}
